development:
  adapter: postgresql
  database: rapi_db_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rapi_db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rapi_db_production
  pool: 5
  timeout: 5000